### ISSUE TITLE
Question: building evidence of subtyping between recursive types

### ISSUE THREAD

**Issue by julbinb** [zmthy/recursive-types#1]
I apologize if the question is trivial:
Is it possible to prove subtyping for any particular example of recursive types?

I could imagine that for `int <: int` we have an `int` constructor, which proves that `Int ≤ Int` (because `∞unfold int = Int`) .
But I cannot see how to deduce a proof for recursive types, for which `∞unfold` gives infinite(?) terms.
Or I may be completely mistaken :)

**Comment by zmthy** [comment]
I think what you're asking is whether it is possible to build a program with the type `Decidable _≤_`. That is, `(A B : Type) → Dec (A ≤ B)`, where `Dec` is either:
- `yes : A ≤ B → Dec (A ≤ B)`
- `no : ¬ A ≤ B → Dec (A ≤ B)`

You're right, such a program could never be implemented. The program would be neither terminating nor productive: since the input is potentially infinite, and the entirety of the input is going to be needed to be inspected in some cases, the output would need to be productive. If the two types are actually subtypes then the entire proof must be constructed before `yes` can be returned, and that entire proof may be infinite in size (and so take infinite time to calculate), so it is impossible to return a piece of the result in finite time.

However, the inductive rendering of types *are* finite in size, so it should be possible to build a program of type `∀ {A B} {p : WellFormed _ A} {q : WellFormed _ B} → Dec (p <: q)`, which in turn would immediately render a proof that `Dec (∞unfold p ≤ ∞unfold q)`. It's something that I wanted to do at the time but never quite got around to (and it's still somewhat complicated).

So the best way of thinking of this is that `(∀ {A} → WellFormed _ A) ⊆ Type`: without an inductive representation into an infinite unfolding, a `Type` is inscrutably infinite. The structure of the type must repeat at some point in order for it to be encoded into Agda, but we can't see *where* the repetition occurs without traversing the entire structure (which is equivalent to saying that we can't see it at all). With the infinite unfolding of the inductive form, we can inspect the inductive structure, which has the repetition encoded into it in a finite, inspectable form.
